name: build-mihomo

on:
  workflow_dispatch:
  push:
    branches:
      - "mihomo"

jobs:
  build-mihomo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert tags to lowercase
        run: |
          ghcr_tag="ghcr.io/${{ github.repository }}"
          echo "ghcr_tag=${ghcr_tag,,}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:dev/v7"
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.ghcr_tag }}:mihomo
            ${{ env.ghcr_tag }}:commit-${{ github.sha }}
